language: node_js
node_js:
- node
- lts/*
notifications:
  email: false
script:
- npm run build
deploy:
  local_dir: build
  skip_cleanup: true
  on:
    node: lts/*
  provider: s3
  bucket: com.shepherdjerred.ec2-instance-restart
  access_key_id: AKIA2CQO232KCPEQDT7X
  secret_access_key:
    secure: bAzcF+APJS4ofa0t88N8GLPm1mG+65iOQ1/resQGuuHW4LVlrk0YyoqHvobrmQAFiAzJXhkktonv8htbzCf7deyWnvODkhIZ4tstoZH9AYcc9PY4YTnw+xm9JKM+EdN1Z1+ED7jgadeRR2UWS+M2zRhHGv7exP/4A0MRU1vSHHV7eygtWV5N33h+J0PR79WtC8zX8juMsVt11/yJCjd2XwZhxtEsY5fli3nCRDkjUOoiNnsxz463b22zdH7M47/xaqNjAnqNpfxzQytMWDSXEa0F7CLVcl0kK9j63sELq9lhV9J8/y4qyGap0Z+jPMeLbnYPpcltNBp0JgdgFt83s2KIuoN9dj9rvD4LPaFZmIL3iz4HZaqSfpO/PperiJTxKZYmMG400UnntjvuJl76O/1rfyhixP2YRI4RJb+EfL0Ezj5BFrZGbsobPenNHYD3CDU3vphEz7PNScwcI+dIiFFw3KTciLBp4cijzk94AejVsRFN1HHKHeG8HoBB5ZQsP3Y3FEZ1hNorYZK6Aw9kanV0o7bDj3VNbbVKoVbD6ehrAlwgjlnk/8olsnu3TG426jvfa/AkLJcjPi8Rwz1XVEJ1UzKor3WIn+FeW+7h1OYLGsQwQPETfhYTfGx6b4y1MCFzfj9DpvqNxrS2mMtT9C+qRiWZ7yNENPv35i5QY4o=
